### ISSUE TITLE
Finish this and put on hackage?

### ISSUE THREAD

**Issue by teh** [Gabriella439/pipes-process#1]
Hi, I've started using this with some modifications because pipes-shell [1] seems to have gone away (github account missing) and pipes-cliff has an awkward interface. Here's what I think is missing to make it work 
- full duplex (this requires `forkIO` in `execute'` IIUC
- A nicer way to allow using `std_out = CreatePipe` (instead of inheriting stdout etc)
- put it on hackage

I'm fairly new to Haskell so my code is quite bad but I could create PR if you think that'd help.
[1]
https://hackage.haskell.org/package/pipes-shell

https://hackage.haskell.org/package/pipes-cliff

**Comment by teh** [comment]
After starting on adding what I need I found process-streaming by googling for related issues which does what I need  and much more. Closing this, apologies for the noise!

**Comment by Gabriella439** [comment]
I also forgot to mention that this package eventually evolved into my `turtle` library, so check that out, too, if you don't need `pipes` specifically.
